### ISSUE TITLE
panic (v2.0.0 - linux) 

### ISSUE THREAD

**Issue by kitej39** [xjasonlyu/tun2socks#22]
Hi.
Falls periodically.  This is observed in the new version.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9d611e]

goroutine 124 [running]:
github.com/xjasonlyu/tun2socks/internal/proxy.(*Socks5).DialContext.func1(0xc000090e58, 0xc000090e48)
	github.com/xjasonlyu/tun2socks/internal/proxy/socks5.go:42 +0x3e
github.com/xjasonlyu/tun2socks/internal/proxy.(*Socks5).DialContext(0xc0001a4510, 0xc31840, 0xc00009fda0, 0xc0000ddab0, 0x0, 0x0, 0xc241a0, 0xc000372440)
	github.com/xjasonlyu/tun2socks/internal/proxy/socks5.go:55 +0x40d
github.com/xjasonlyu/tun2socks/internal/proxy.Dial(0xc0000ddab0, 0x0, 0x0, 0x0, 0x0)
	github.com/xjasonlyu/tun2socks/internal/proxy/proxy.go:63 +0xaf
github.com/xjasonlyu/tun2socks/internal/tunnel.handleTCP(0xc38e80, 0xc0002e7500)
	github.com/xjasonlyu/tun2socks/internal/tunnel/tcp.go:37 +0x158
created by github.com/xjasonlyu/tun2socks/internal/tunnel.process
	github.com/xjasonlyu/tun2socks/internal/tunnel/tunnel.go:65 +0xc7
```
You have removed the backendDNS in new vers.  What is the default  dns address in the new version?

**Comment by xjasonlyu** [comment]
Thank you for your feedback! This will be fixed soon.

> You have removed the backendDNS in new vers. What is the default dns address in the new version?

system nameserver by default
