### ISSUE TITLE
use v2.2.1,  get panic: unaligned 64-bit atomic operation

### ISSUE THREAD

**Issue by liuxc0116** [xjasonlyu/tun2socks#55]
run tun2socks-linux-mipsle-softfloat-v2.2.1, get panic.

```
panic: unaligned 64-bit atomic operation

goroutine 7 [running]:
runtime/internal/atomic.panicUnaligned(...)
        runtime/internal/atomic/unaligned.go:8
runtime/internal/atomic.lockAndCheck(...)
        runtime/internal/atomic/atomic_mipsx.go:37
runtime/internal/atomic.Store64(0x11ec41c, 0x100000, 0x0)
        runtime/internal/atomic/atomic_mipsx.go:103 +0x94
gvisor.dev/gvisor/pkg/atomicbitops.(*AlignedAtomicInt64).Store(...)
        gvisor.dev/gvisor@v0.0.0-20210528151111-2153eaa44276/pkg/atomicbitops/aligned_64bit.go:39
gvisor.dev/gvisor/pkg/tcpip.(*SocketOptions).SetSendBufferSize(0x11ec3b0, 0x100000, 0x0, 0x72c900)
        gvisor.dev/gvisor@v0.0.0-20210528151111-2153eaa44276/pkg/tcpip/socketops.go:626 +0x19c
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.newEndpoint(0x1115180, 0x800, 0x11e20c0, 0x4)
        gvisor.dev/gvisor@v0.0.0-20210528151111-2153eaa44276/pkg/tcpip/transport/tcp/endpoint.go:840 +0x208
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*listenContext).createConnectingEndpoint(0x1222000, 0x1282000, 0x11b3f74, 0x11e20c0, 0x1018150, 0x4, 0x521ba4)
        gvisor.dev/gvisor@v0.0.0-20210528151111-2153eaa44276/pkg/tcpip/transport/tcp/accept.go:216 +0xcc
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*listenContext).startHandshake(0x1222000, 0x1282000, 0x11b3f74, 0x11e20c0, 0x0, 0x0, 0x0, 0x0, 0x0)
        gvisor.dev/gvisor@v0.0.0-20210528151111-2153eaa44276/pkg/tcpip/transport/tcp/accept.go:251 +0xe4
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*listenContext).performHandshake(0x1222000, 0x1282000, 0x11b3f74, 0x11e20c0, 0x0, 0x0, 0x18, 0x77f17790, 0x18)
        gvisor.dev/gvisor@v0.0.0-20210528151111-2153eaa44276/pkg/tcpip/transport/tcp/accept.go:327 +0x68
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*ForwarderRequest).CreateEndpoint(0x1014120, 0x11e20c0, 0x0, 0x0, 0x0, 0x0)
        gvisor.dev/gvisor@v0.0.0-20210528151111-2153eaa44276/pkg/tcpip/transport/tcp/forwarder.go:155 +0x12c
github.com/xjasonlyu/tun2socks/core/stack.withTCPHandler.func1.1(0x1014120)
        github.com/xjasonlyu/tun2socks/core/stack/tcp.go:40 +0xf8
created by gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*Forwarder).HandlePacket
        gvisor.dev/gvisor@v0.0.0-20210528151111-2153eaa44276/pkg/tcpip/transport/tcp/forwarder.go:94 +0x334
```

**Comment by xjasonlyu** [comment]
Gotta wait gVisor to fix it.
